AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Route53 hosted zone, ACM certificate, and DNS validation"

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: mirzaakhena.com

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: mirzaakhena.com
      SubjectAlternativeNames:
        - "*.mirzaakhena.com"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: mirzaakhena.com
          HostedZoneId: !Ref HostedZone

Outputs:
  HostedZoneId:
    Description: "Hosted Zone ID"
    Value: !Ref HostedZone
  NameServers:
    Description: "Name Servers for the Hosted Zone"
    Value: !Join
      - ", "
      - !GetAtt HostedZone.NameServers
  CertificateArn:
    Description: "ARN of the created certificate"
    Value: !Ref Certificate
